### ISSUE TITLE
Network Signal on Low Battery

### ISSUE THREAD

**Issue by saiz136** [milaq/android_device_lge_p940#20]
When my battery reach level 20% or 15% (not quite sure) the network disconnects although the status bar shows with bars. Airplane mode doesn't help to reconnect, but a reboot sure refreshes back the network.

**Comment by stealthmopped** [comment]
The problem is old. It was already there, as I used the original rom 4.04. The problem is getting bigger with time. In the beginning it happend with 10% battery, now it happens with about 25%. It seems, that it happens by less than 3,700 V battery-voltage. Maybe there is a problem with the voltage stabilization...??? Reboot or flight-mode does not work properly

**Comment by ghost** [comment]
When it happens by less than 3,700 V - wouldn't it be possible to overclock this somehow?

**Comment by stealthmopped** [comment]
I don't know. 
First, I buy a now Accupack and report what happens. 
How old are your devices and Accupacks ?

**Comment by ghost** [comment]
I bought my device 05.2012. My battery is as old as my device.

**Comment by stealthmopped** [comment]
I bought my device 07.2012 
Original, first battery.
The problem occurs at less than 3,7V

**Comment by ghost** [comment]
Wow, it seems you're right. My battery level is at 71 % right now and I started many apps at the same time to "overuse" my phone. The battery voltage decreased to ~3,4 V and I tried to toogle 2G/3G, didn't work - network issues.
After restart it's 3741 mV and network is working again.

EDIT: Okay, my battery level is 10 % and the battery voltage is 3743 mV ..and yet I have network issues again.. :/

**Comment by stealthmopped** [comment]
First test with new battery is done. 
My networkproblem is fixed, at the moment and the Voltage is under 3,7V, but it works.
Only the voltage doesn't say enough...
Regularly go till zero percent is not very nicely for the battery.

**Comment by saiz136** [comment]
So you mean to say it is not on ROM either custom CM or stock but the battery itself?

**Comment by stealthmopped** [comment]
Yes, it seems so

**Comment by saiz136** [comment]
Sorry I clicked closed, hahaha reponed already! Anyway, I was about to download and flash stock GB ROM V10 kdz image, but you stated that this is a hardware fault? So flashing GB is useless and will still show the same result?

**Comment by stealthmopped** [comment]
I used a new polarcell-battery for the test.
Now I'm charging.
I will report after second test.

**Comment by ghost** [comment]
Do you need a new back cover to use the polarcell-battery? Is it the "1700mAh"-battery?

**Comment by stealthmopped** [comment]
No new backcover needed, Yes the 1700 mAh-Battery.
The original should work as well.
As my device was new with the original-battery it also worked

**Comment by saiz136** [comment]
@stealthmopped so you mean to say the easiest, we need a new battery with 1700 mAh to fix the issue? Or a possible fix on some parameters on the  kernel or ROM?

**Comment by stealthmopped** [comment]
Second test done with no problems.
I have tested till 4% and no disconnections.
A test with a new cheap powermaxx-battery a few weeks ago ends by about 15%.
My original, old battery only goes till about 30%.

The battery is the problem. :-)

Our Phones react very sensitive to bad batteries.
Don't let them go regulary under 20 % !!!

best regards

**Comment by milaq** [comment]
a shit voltage regulator in combination with the modem is the culprit here.

batteries shouldn't pose a problem. it is just that the modem can't op correctly on voltages lower than a certain threshold (supposedly 3.4volts)

**Comment by stealthmopped** [comment]
Yes for sure. But a good, new battery helps to avoid the problem.

**Comment by milaq** [comment]
tagged as wontfix

**Comment by stealthmopped** [comment]
Nevertheless, thank you for your great work !!!

**Comment by saiz136** [comment]
@stealthmopped However after a reboot, my network connection is back although from 20% after reboot my power was cut into half or 2/3 of 20%!
